"""
Turn Natural Earth 110m land polygons into one inline SVG path.

Public domain source (naturalearthdata.com), fetched once to _source/. The output
is written to content/worldmap.json and embedded by build.py, so the site never
calls out to a tile server or a mapping library at runtime.

Projection is equirectangular on purpose. y stays linear in latitude, so the
Arctic Circle and the tropics remain straight horizontal lines and the section
keeps the point it was making before it had coastlines.

    python tools/gen_worldmap.py
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "_source" / "ne_110m_land.geojson"
OUT = ROOT / "content" / "worldmap.json"

# Viewport in degrees. Antarctica and the high Arctic are dropped: she has
# raced at neither, and they cost a third of the height.
LAT_TOP, LAT_BOT = 84.0, -58.0
TOLERANCE = 0.30    # Douglas-Peucker, in degrees
MIN_AREA = 3.0      # square degrees; drops specks that read as dirt


def project(lon, lat):
    return (lon + 180.0, LAT_TOP - lat)


def perp_dist(p, a, b):
    (x, y), (x1, y1), (x2, y2) = p, a, b
    dx, dy = x2 - x1, y2 - y1
    if dx == 0 and dy == 0:
        return ((x - x1) ** 2 + (y - y1) ** 2) ** 0.5
    t = ((x - x1) * dx + (y - y1) * dy) / (dx * dx + dy * dy)
    t = max(0.0, min(1.0, t))
    return ((x - (x1 + t * dx)) ** 2 + (y - (y1 + t * dy)) ** 2) ** 0.5


def simplify(pts, tol):
    """Douglas-Peucker, iterative so a long coastline cannot blow the stack."""
    if len(pts) < 3:
        return pts
    keep = [False] * len(pts)
    keep[0] = keep[-1] = True
    stack = [(0, len(pts) - 1)]
    while stack:
        lo, hi = stack.pop()
        worst, idx = 0.0, -1
        for i in range(lo + 1, hi):
            d = perp_dist(pts[i], pts[lo], pts[hi])
            if d > worst:
                worst, idx = d, i
        if idx != -1 and worst > tol:
            keep[idx] = True
            stack.append((lo, idx))
            stack.append((idx, hi))
    return [p for p, k in zip(pts, keep) if k]


def shoelace(pts):
    a = 0.0
    for i in range(len(pts) - 1):
        a += pts[i][0] * pts[i + 1][1] - pts[i + 1][0] * pts[i][1]
    return abs(a) / 2.0


def ring_to_path(ring):
    pts = [project(lon, lat) for lon, lat in ring]
    # Clip vertically to the viewport rather than dropping whole shapes.
    top, bot = 0.0, LAT_TOP - LAT_BOT
    pts = [(x, max(top, min(bot, y))) for x, y in pts]
    pts = simplify(pts, TOLERANCE)
    if len(pts) < 4 or shoelace(pts) < MIN_AREA:
        return None
    head = f"M{pts[0][0]:.2f} {pts[0][1]:.2f}"
    rest = "".join(f"L{x:.2f} {y:.2f}" for x, y in pts[1:])
    return head + rest + "Z"


def main() -> int:
    if not SRC.exists():
        raise SystemExit(f"missing {SRC}")
    # utf-8-sig: PowerShell's Out-File writes a BOM.
    gj = json.loads(SRC.read_text(encoding="utf-8-sig"))

    rings = []
    for feat in gj["features"]:
        geom = feat["geometry"]
        polys = (
            geom["coordinates"]
            if geom["type"] == "MultiPolygon"
            else [geom["coordinates"]]
        )
        for poly in polys:
            for ring in poly:  # outer ring plus any holes
                d = ring_to_path(ring)
                if d:
                    rings.append(d)

    path = "".join(rings)
    payload = {
        "note": "Natural Earth 110m land, public domain. Generated by tools/gen_worldmap.py.",
        "projection": "equirectangular",
        "viewBox": f"0 0 360 {LAT_TOP - LAT_BOT:.0f}",
        "latTop": LAT_TOP,
        "latBottom": LAT_BOT,
        "path": path,
    }
    OUT.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"{len(rings)} rings, path {len(path) / 1024:.1f} KB -> {OUT.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
